### ISSUE TITLE
it don't work on CH32V307

### ISSUE THREAD

**Issue by crazyuav** [ArcaneNibble/wch-uf2#1]
I tested on CH32V307,but it don't work.
Which development board are you using?

**Comment by ArcaneNibble** [comment]
Hi, thank you for taking the time to report an issue!

To answer your immediate question, this code was tested on the vendor's (horribly designed) CH32V**203**C8T6 dev board (the EVT, requiring an A-A cable) and on custom boards featuring a CH32V**203**G6U6.

The problem with the CH32V307 is that it doesn't have the specific "USBD" peripheral which this code uses. It has a peripheral variously labeled "USBFS" or "OTG_FS"  which is completely different with a different register interface. It also has "USBHS" which is likewise unsupported. Unfortunately, this means that this code simply cannot be used on the CH32V307.

Looking through the reference manual, it would appear that no 3xx part actually has the "USBD" peripheral, despite the note at the top of Chapter 21 referencing CH32V3x. I'm going to leave this issue open as a reminder for me to update the README appropriately.
